services:

  db:
    image: mysql:8
    container_name: pmt-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pmt
      - CHARACTER_SET_SERVER=utf8mb4
      - COLLATION_SERVER=utf8mb4_general_ci
      - TZ=Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/schema_pmt.sql:/docker-entrypoint-initdb.d/schema_pmt.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmt-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

  mailpit:
    image: axllent/mailpit:latest
    container_name: pmt-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"   # UI web -> http://localhost:8025
      - "1025:1025"   # SMTP

  backend:
    build:
      context: ./pmt-backend
      dockerfile: Dockerfile
    container_name: pmt-backend
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pmt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # SMTP (assure l'envoi de mails vers Mailpit)
      APP_NOTIFICATIONS_ENABLED: "true"
      APP_FRONTEND_URL: "http://localhost:4200"
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: "1025"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_FROM: "no-reply@pmt.local"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10

  frontend:
    build:
      context: ./pmt-frontend
      dockerfile: Dockerfile
    container_name: pmt-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:80"

volumes:
  db_data: